### ISSUE TITLE
File unusable

### ISSUE THREAD

**Issue by jedhassell** [0dan0/udtacopy#1]
I am following the instructions listed here: https://gopro.github.io/labs/control/chapters/

```
ffmpeg -y -f concat -i your_path_to/filelist.txt -c copy -map 0:0 -map 0:1 -map 0:3 your_output_path/final.mp4
udtacopy your_path_to/the_first_GoPro_file.MP4 your_output_path/final.mp4
```

After running `udtacopy`, my final file is unusable and realsteady is unable to load the file.

**Comment by dnewman-gpsw** [comment]
As it works here and has been confirmed to work for others, you will need to provide more information.

**Comment by jedhassell** [comment]
Thank you for responding so quickly!  Please let me know what information would be useful.  I can also provide the files for you if needed.  

Commands I am running
* `ffmpeg -y -f concat -i filelist.txt -c copy -map 0:0 -map 0:1 -map 0:3 test3.mp4` 
  * I am able to play `test3.mp4`
* `./udtacopy GX010103.MP4 test3.mp4`
  * `test3.mp4` isn't playable or readable by reasteady

Contents of filelist.txt
```
file 'GX010103.mp4'
file 'GX020103.MP4'
```

**Comment by dnewman-gpsw** [comment]
- What platform are you on?  
- Does the final test3.mp4 open in VLC or similar?
- use ffprobe on test3.mp4 before and after using udtacopy.  Add send me that output.  This is a faster step than sending the files. I'm willing to look at the files.

udtacopy does very little, simply copies the missing atom to the end of test3.mp4.  RSGo may have other reasons to reject the file.

**Comment by jedhassell** [comment]
> * What platform are you on?
> * Does the final test3.mp4 open in VLC or similar?
> * use ffprobe on test3.mp4 before and after using udtacopy.  Add send me that output.  This is a faster step than sending the files. I'm willing to look at the files.
> 
> udtacopy does very little, simply copies the missing atom to the end of test3.mp4. RSGo may have other reasons to reject the file.

* I'm running MacOS Catalina
* It does open in VLC but it takes a while so I'm not sure what it's doing during load.  
* output from ffprobe before `./udtacopy GX010103.MP4 test3.mp4`
```
ffprobe test3.mp4 
ffprobe version 4.4 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.29)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test3.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.76.100
  Duration: 00:19:06.50, start: 0.000000, bitrate: 100059 kb/s
  Stream #0:0(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 2704x2028 [SAR 1:1 DAR 4:3], 99808 kb/s, 59.94 fps, 59.94 tbr, 60k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : GoPro H.265
      vendor_id       : [0][0][0][0]
      timecode        : 09:45:43:51
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s (default)
    Metadata:
      handler_name    : GoPro AAC  
      vendor_id       : [0][0][0][0]
  Stream #0:2(eng): Data: bin_data (gpmd / 0x646D7067), 49 kb/s
    Metadata:
      handler_name    : GoPro MET  
  Stream #0:3(eng): Data: none (tmcd / 0x64636D74)
    Metadata:
      handler_name    : GoPro H.265
      timecode        : 09:45:43:51
Unsupported codec with id 100359 for input stream 2
Unsupported codec with id 0 for input stream 3
```
* output of ffprobe after `./udtacopy GX010103.MP4 test3.mp4`
```
ffprobe test3.mp4 
ffprobe version 4.4 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.29)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fa607818000] Detected moov in a free or hoov atom.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test3.mp4':
  Metadata:
    minor_version   : 512
    major_brand     : isom
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.76.100
    firmware        : HD8.01.02.50.71
  Duration: 00:19:06.50, start: 0.000000, bitrate: 100059 kb/s
  Stream #0:0(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 2704x2028 [SAR 1:1 DAR 4:3], 99808 kb/s, 59.94 fps, 59.94 tbr, 60k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : GoPro H.265
      vendor_id       : [0][0][0][0]
      timecode        : 09:45:43:51
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s (default)
    Metadata:
      handler_name    : GoPro AAC  
      vendor_id       : [0][0][0][0]
  Stream #0:2(eng): Data: bin_data (gpmd / 0x646D7067), 49 kb/s
    Metadata:
      handler_name    : GoPro MET  
  Stream #0:3(eng): Data: none (tmcd / 0x64636D74)
    Metadata:
      handler_name    : GoPro H.265
      timecode        : 09:45:43:51
Unsupported codec with id 100359 for input stream 2
Unsupported codec with id 0 for input stream 3
```

**Comment by dnewman-gpsw** [comment]
So the file is valid and only RSGo doesn't like it?  Look like everything worked.  You can use https://github.com/0dan0/mp4struct/blob/main/mp4struct.zip  to validate the udta fix.

Before udtacopy
```
$ mp4struct /d/temp/test3org.mp4
 ftyp (32)
 free (8)
 mdat (3211119767)
 moov (225985)
...
    98  udta (98)
```

After udtacopy
```
$ mp4struct /d/temp/test3.mp4
 ftyp (32)
 free (8)
 mdat (3211119767)
 moov (252406)
...
 26519  free (98)
 26421  udta (26421)
```

Other reasons for RSGo not loading is not my area, I haven't worked in that code. Sometime it doesn't like some framerate on older cameras.  With ffmpeg and udtacopy, this is a valid MP4 with all the GoPro metadata. 

Which camera model is this?

**Comment by jedhassell** [comment]
It looks like QT isn't able to open it but VLC is.  

I am using a Hero8 with gopro labs installed on it.  Would you be willing to take a stab at loading it into RSGo using the two files?  I can send you a share link with them.

**Comment by dnewman-gpsw** [comment]
Send me a link to the files.

**Comment by jedhassell** [comment]
Here's 2 files: https://www.amazon.com/clouddrive/share/zmXHmY79LUMvwRpwcqxyxD5lqhEw93vxWPWvLgCRxD0
Let me know if you can't download them.

**Comment by dnewman-gpsw** [comment]
It works here.  I'm testing on Windows.  RSGo is rendering now, that will take a while.

**Comment by jedhassell** [comment]
That's interesting.  Do you have a mac to test on?  I am posting the md5's of the files as I go through the workflow to see if there is any divergence from your workflow.  If your `test3.mp4` final file has the same md5, it must be a RSGo issue.  If not, you could send me your `test3.mp4` file and I can test on RSGo on my mac to prove if there's an issue somewhere in the workflow.

```
MD5 (GX010103.MP4) = 122f99e852234babe1658d186905fdfb
MD5 (GX020103.MP4) = 640e39985314f3b7a2435ceb25128cc7
```
before `./udtacopy GX010103.MP4 test3.mp4`
`MD5 (test3.mp4) = 3459b44bf1ca4f2e53b084aa38502dea`

after `./udtacopy GX010103.MP4 test3.mp4`
`MD5 (test3.mp4) = 5c43072c018456f61165b28dc6c3be31`

**Comment by dnewman-gpsw** [comment]
There was a bug in the Mac version of udtacopy.   

Download v1.03 from https://github.com/gopro/labs/blob/master/docs/control/chapters/bin/udtacopy.zip

If you had used the **mp4struct** you can see the problem immediately.

after using udtacopy v1.02
mp4struct Y:\join.mp4
 ftyp (28)
 mdat (14338026546)
 free (1752279)
  
vs
after using udtacopy v1.03
mp4struct Y:\join.mp4
 ftyp (28)
 mdat (14338026546)
 moov (1752279)
 1752271  mvhd (108)
 1752163  trak (1065493)
 1752155  1065485  tkhd (92)
 1752063  1065393  edts (36)
 1752027  1065357  tref (20)
 1752007  1065337  mdia (1065337)
 1751999  1065329  1065329  mdhd (32)
 1751967  1065297  1065297  hdlr (45)
 1751922  1065252  1065252  minf (1065252)
 1751914  1065244  1065244  1065244  vmhd (20)
 1751894  1065224  1065224  1065224  dinf (36)
 1751886  1065216  1065216  1065216     28  dref (28)
 1751858  1065188  1065188  1065188  stbl (1065188)
 1751850  1065180  1065180  1065180  1065180  stsd (284)
 type/subtype: vide/hvc1
 1751566  1064896  1064896  1064896  1064896  stts (40)
 1751526  1064856  1064856  1064856  1064856  stss (4600)
 1746926  1060256  1060256  1060256  1060256  stsc (353356)
 1393570  706900  706900  706900  706900  stsz (274900)
 1118670  432000  432000  432000  432000  co64 (432000)
 686670  trak (645461)
 686662  645453  tkhd (92)
 686570  645361  edts (36)
 686534  645325  mdia (645325)
 686526  645317  645317  mdhd (32)
 686494  645285  645285  hdlr (45)
 686449  645240  645240  minf (645240)
 686441  645232  645232  645232  smhd (16)
 686425  645216  645216  645216  dinf (36)
 686417  645208  645208  645208     28  dref (28)
 686389  645180  645180  645180  stbl (645180)
 686381  645172  645172  645172  645172  stsd (126)
 type/subtype: soun/mp4a
 686255  645046  645046  645046  645046  stts (24)
 686231  645022  645022  645022  645022  stsc (28)
 686203  644994  644994  644994  644994  stsz (214988)
 471215  430006  430006  430006  430006  co64 (429952)
 41263     54     54     54     54  sgpd (26)
 41237     28     28     28     28  sbgp (28)
 41209  trak (14261)
 41201  14253  tkhd (92)
 41109  14161  edts (36)
 41073  14125  mdia (14125)
 41065  14117  14117  mdhd (32)
 41033  14085  14085  hdlr (45)
 40988  14040  14040  minf (14040)
 40980  14032  14032  14032  gmhd (88)
 40892  13944  13944  13944  dinf (36)
 40884  13936  13936  13936     28  dref (28)
 40856  13908  13908  13908  stbl (13908)
 40848  13900  13900  13900  13900  stsd (36)
 type/subtype: meta/gpmd
 40812  13864  13864  13864  13864  stts (48)
 40764  13816  13816  13816  13816  stsc (28)
 40736  13788  13788  13788  13788  stsz (4604)
 36132   9184   9184   9184   9184  co64 (9184)
 26948  trak (429)
 26940    421  tkhd (92)
 26848    329  edts (36)
 26812    293  mdia (293)
 26804    285    285  mdhd (32)
 26772    253    253  hdlr (45)
 26727    208    208  minf (208)
 26719    200    200    200  nmhd (12)
 26707    188    188    188  dinf (36)
 26699    180    180    180     28  dref (28)
 26671    152    152    152  stbl (152)
 26663    144    144    144    144  stsd (52)
 type/subtype: tmcd/tmcd
 26611     92     92     92     92  stts (24)
 26587     68     68     68     68  stsc (28)
 26559     40     40     40     40  stsz (20)
 26539     20     20     20     20  stco (20)
 26519  free (98)
 26421  udta (26421)

Should be all good now.

**Comment by jedhassell** [comment]
I confirm it now works!  Thanks for your help on this.  This is such a nice tool for long recordings.  I'll be sure to spread it around the FPV community :)

**Comment by dayyan** [comment]
kewl
